from MetricItem import MetricItem

def make_smu_metrics():
    # Yes/No questions
    yield MetricItem('V1', 'أسرة مكونة من فرد واحد، أو من زوجين بدون أطفال', 0.103, 'checkbox')
    yield MetricItem('V2', 'أسرة مكونة من أكثر من نواة عائلية', 0.035, 'checkbox')
    yield MetricItem('V3', 'غرفة واحدة يتقاسمها شخصان على الأكثر', 0.0475, 'checkbox')
    yield MetricItem('V4', 'سكن الأسرة يتوفرعلى حمام أورشاش', 0.096, 'checkbox')
    yield MetricItem('V5', 'سكن الأسرة يتوفر على عداد فردي للكهرباء', 0.0466, 'checkbox')
    yield MetricItem('V6', 'يتوفررب الأسرة على مستوى تعليمي عالي', 0.0806, 'checkbox')
    yield MetricItem('V7', 'رب الأسرة إطارعالي أويشغل منصب مسؤولية', 0.0782, 'checkbox')
    yield MetricItem('V8', 'رب الأسرة إطار متوسط', 0.110, 'checkbox')
    yield MetricItem('V9', 'رب الأسرة مشغل', 0.182, 'checkbox')
    yield MetricItem('V10', 'رب الأسرة متقاعد أو يستفيد من إيراد', 0.0605, 'checkbox')
    yield MetricItem('V11', 'تتوفر الأسرة على حاسوب أو أكثر', 0.138, 'checkbox')
    yield MetricItem('V12', 'تتوفر الأسرة على القط هوائي', 0.0873, 'checkbox')
    yield MetricItem('V13', 'الأسرة تتوفر على هاتف ثابت', 0.0532, 'checkbox')
    yield MetricItem('V14', 'يستفيد فرد واحد من الأسرة على الأقل من نظام التغطية الصحية غير نظام ملساعدة الطبية )راميد(', 0.151, 'checkbox')
    yield MetricItem('V15', 'تستفيد الأسرة من قرض لدى إحدى األبناك أو املؤسسات املالية أو املشغل', 0.135, 'checkbox')
    yield MetricItem('V16', 'تتوفرالأسرة على سكن ثانوي', 0.173, 'checkbox')
    yield MetricItem('V17', 'تتوفر الأسرة على مرآب', 0.117, 'checkbox')
    yield MetricItem('V18', 'تتوفر الأسرة على محالت مهنية', 0.111, 'checkbox')

    # Quantity questions
    yield MetricItem('V19', 'عدد أفراد الأسرة', -0.177, 'text-input')
    yield MetricItem('V20', 'مربع عدد أفراد الأسرة', 0.00533, 'text-input')
    yield MetricItem('V21', 'سن رب الأسرة', -0.0104, 'text-input')
    yield MetricItem('V22', 'مربع سن رب الأسرة', 0.0000771, 'text-input')
    yield MetricItem('V23', 'عدد الأطفال املتمدرسين في القطاع الخاص الذين تتراوح أعمارهم ما بين 6 و 14 سنة', 0.105, 'text-input')
    yield MetricItem('V24', 'عدد الأطفال املتمدرسين في القطاع العمومي الذين تتراوح أعمارهم ما بين 6 و 14 سنة', -0.0319, 'text-input')
    yield MetricItem('V25', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثر والذين لا يتوفرون على أي شهادة', -0.0557, 'text-input')
    yield MetricItem('V26', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثر الحاصلين على شهادة أو دبلوم تقني', 0.120, 'text-input')
    yield MetricItem('V27', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثرالذين يزاولون نشاطا مدرا للدخل', 0.139, 'text-input')
    yield MetricItem('V28', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثرالذين يزاولون نشاط تسيير للمعدات', 0.307, 'text-input')
    yield MetricItem('V29', 'نسبة أفراد الأسرة الذين يشتغلون كأطر عليا أو يشغلون منصب مسؤولية', 0.180, 'text-input')
    yield MetricItem('V30', 'عدد الهواتف المحمولة داخل الأسرة', 0.0516, 'text-input')
    yield MetricItem('V31', 'عدد السيارات في حوزة الأسرة', 0.226, 'text-input')
    yield MetricItem('V32', 'عدد الدراجات النارية', 0.0598, 'text-input')
    yield MetricItem('V33', 'مبلغ مصاريف الأسرة السنوية المتعلقة باستهالك غازالبوتان مقسوم على عدد أفراد الأسرة', 0.000422, 'text-input')
    yield MetricItem('V34', 'مبلغ مصاريف الأسرة السنوية المتعلقة باستهالك املاء والكهرباء مقسوم على عدد أفراد الأسرة', 0.00011, 'text-input')
    yield MetricItem('V35', 'مبلغ مصاريف لألسرة السنوية المتعلقة باستهالك الهاتف او إلنترنت مقسوم على عدد أفراد الأسرة', 0.000302, 'text-input')

    # Select questions
    yield MetricItem('KZG1', 'طنجة-تطوان-الحسيمة', 0.107, 'select-input')
    yield MetricItem('KZG2', 'الشرق', 0.196, 'select-input')
    yield MetricItem('KZG3', 'فاس-مكناس', 0.123, 'select-input')
    yield MetricItem('KZG4', 'الرباط - سال- القنيطرة', 0.0555, 'select-input')
    yield MetricItem('KZG5', 'بني مالل - خنيفرة', 0.0, 'select-input')
    yield MetricItem('KZG6', 'الدار البيضاء - سطات', 0.220, 'select-input')
    yield MetricItem('KZG7', 'مراكش - آسفي', 0.194, 'select-input')
    yield MetricItem('KZG8', 'درعة - تافياللت', 0.0, 'select-input')
    yield MetricItem('KZG9', 'سوس - ماسة', 0.0, 'select-input')
    yield MetricItem('KZG10', 'كلميم - واد نون', 0.285, 'select-input')
    yield MetricItem('KZG11', 'العيون-الساقية الحمراء ', 0.285, 'select-input')
    yield MetricItem('KZG12', 'الداخلة-وادي الذهبرة', 0.285, 'select-input')




def make_smr_metrics():
    # Yes/No questions
    yield MetricItem('V1', 'أسرة مكونة من فرد واحد، أو من زوجين بدون أطفال', 0.130, 'checkbox')
    yield MetricItem('V2', 'أسرة تقيم بفيلا، شقة، دار تقليدية، دار قروية مشيدة بالأحجار اليابسة، أو بالأحجار المغطاة بالطين', 0.127, 'checkbox')
    yield MetricItem('V3', 'غرفة واحدة يتقاسمها شخصان على الأكثر', 0.129, 'checkbox')
    yield MetricItem('V4', 'غرفة واحدة يتقاسمها ثلاثة أشخاص على الأكثر', 0.108, 'checkbox')
    yield MetricItem('V5', 'يتوفر رب الأسرة على مستوى تعليمي أساسي', 0.0569, 'checkbox')
    yield MetricItem('V6', 'رب الأسرة إطار عالي أو يشغل منصب مسؤولية', 0.154, 'checkbox')
    yield MetricItem('V7', 'رب الأسرة مسير للمعدات أو الآلات الثابتة', 0.196, 'checkbox')
    yield MetricItem('V8', 'رب الأسرة حرفي', 0.125, 'checkbox')
    yield MetricItem('V9', 'رب الأسرة مستغل فلاحي', 0.0722, 'checkbox')
    yield MetricItem('V10', 'رب الأسرة مشغل', 0.190, 'checkbox')
    yield MetricItem('V11', 'الأسرة تمتلك سيارة', 0.187, 'checkbox')
    yield MetricItem('V12', 'الأسرة تمتلك دراجة نارية', 0.0635, 'checkbox')
    yield MetricItem('V13', 'يستفيد فرد واحد من الأسرة على الأقل من نظام للتغطية الصحية غير نظام المساعدة الطبية', 0.193, 'checkbox')
    yield MetricItem('V14', 'تتوفر الأسرة على سكن ثانوي', 0.334, 'checkbox')
    yield MetricItem('V15', 'تتوفر الأسرة على أراض غير فلاحية', 0.233, 'checkbox')
    yield MetricItem('V16', 'تتوفر الأسرة على أرض مسقية أو تستغلها', 0.126, 'checkbox')

    # Quantity questions
    yield MetricItem('V17', 'عدد أفراد الأسرة', -0.138, 'text-input')
    yield MetricItem('V18', 'مربع عدد أفراد الأسرة', 0.00469, 'text-input')
    yield MetricItem('V19', 'عدد أفراد الأسرة الذين تتراوح أعمارهم ما بين 19 و 29 سنة', 0.0523, 'text-input')
    yield MetricItem('V20', 'عدد أفراد الأسرة الذين تتراوح أعمارهم بين 30 و 59 سنة', 0.0337, 'text-input')
    yield MetricItem('V21', 'عدد أفراد الأسرة الذين تبلغ أعمارهم 60 سنة فأكثر', 0.0781, 'text-input')
    yield MetricItem('V22', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثر والذين يستطيعون القراءة والكتابة', 0.128, 'text-input')
    yield MetricItem('V23', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثر الحاصلين على شهادة التعليم العالي', 0.344, 'text-input')
    yield MetricItem('V24', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثر الذين يزاولون التجارة', 0.301, 'text-input')
    yield MetricItem('V25', 'عدد الأبقار التي تمتلكها الأسرة', 0.0257, 'text-input')
    yield MetricItem('V26', 'مبلغ مصاريف الأسرة السنوية المتعلقة باستهلاك غاز البوتان مقسوم على عدد أفراد الأسرة', 0.000755, 'text-input')
    yield MetricItem('V27', 'مبلغ مصاريف الأسرة السنوية المتعلقة باستهلاك الماء والكهرباء مقسوم على عدد أفراد الأسرة', 0.000145, 'text-input')
    yield MetricItem('V28', 'مبلغ مصاريف للأسرة السنوية المتعلقة باستهلاك الهاتف والإنترنت مقسوم على عدد أفراد الأسرة', 0.00086, 'text-input')
    
    # Select question
    yield MetricItem('KZG1', 'طنجة-تطوان-الحسيمة', 0.420, 'select-input')
    yield MetricItem('KZG2', 'الشرق', 0.230, 'select-input')
    yield MetricItem('KZG3', 'فاس-مكناس', 0.296, 'select-input')
    yield MetricItem('KZG4', 'الرباط - سلا- القنيطرة', 0.302, 'select-input')
    yield MetricItem('KZG5', 'بني ملال - خنيفرة', 0.351, 'select-input')
    yield MetricItem('KZG6', 'الدار البيضاء - سطات', 0.464, 'select-input')
    yield MetricItem('KZG7', 'مراكش - آسفي', 0.377, 'select-input')
    yield MetricItem('KZG8', 'درعة - تافيلالت', 0, 'select-input')
    yield MetricItem('KZG9', 'سوس - ماسة', 0.221, 'select-input')
    yield MetricItem('KZG10', 'كلميم - واد نون', 0.318, 'select-input')
    yield MetricItem('KZG11', 'العيون -الساقية الحمراء', 0.318, 'select-input')
    yield MetricItem('KZG12', 'الداخلة-وادي الذهب', 0.318, 'select-input')
