from MetricItem import MetricItem

def make_smu_metrics():
    # Yes/No questions
    yield MetricItem('V1', 'أسرة مكونة من فرد واحد، أومن زوجين بدون أطفال', 0.103, 'checkbox')
    yield MetricItem('V2', 'أسرة مكونة من أكثر من نواة عائلية', 0.035, 'checkbox')
    yield MetricItem('V3', 'غرفة واحدة يتقاسمها شخصان على الأكثر', 0.0475, 'checkbox')
    yield MetricItem('V4', 'سكن الأسرة يتوفرعلى حمام أورشاش', 0.096, 'checkbox')
    yield MetricItem('V5', 'سكن الأسرة يتوفر على عداد فردي للكهرباء', 0.0466, 'checkbox')
    yield MetricItem('V6', 'يتوفررب الأسرة على مستوى تعليمي عالي', 0.0806, 'checkbox')
    yield MetricItem('V7', 'رب الأسرة إطارعالي أويشغل منصب مسؤولية', 0.0782, 'checkbox')
    yield MetricItem('V8', 'رب الأسرة إطار متوسط', 0.110, 'checkbox')
    yield MetricItem('V9', 'رب الأسرة مشغل', 0.182, 'checkbox')
    yield MetricItem('V10', 'رب الأسرة متقاعد أو يستفيد من إيراد', 0.0605, 'checkbox')
    yield MetricItem('V11', 'تتوفر الأسرة على حاسوب أو أكثر', 0.138, 'checkbox')
    yield MetricItem('V12', 'تتوفر الأسرة على القط هوائي', 0.0873, 'checkbox')
    yield MetricItem('V13', 'الأسرة تتوفر على هاتف ثابت', 0.0532, 'checkbox')
    yield MetricItem('V14', 'يستفيد فرد واحد من الأسرة على الأقل من نظام التغطية الصحية غير نظام ملساعدة الطبية )راميد(', 0.151, 'checkbox')
    yield MetricItem('V15', 'تستفيد الأسرة من قرض لدى إحدى األبناك أو املؤسسات املالية أو املشغل', 0.135, 'checkbox')
    yield MetricItem('V16', 'تتوفرالأسرة على سكن ثانوي', 0.173, 'checkbox')
    yield MetricItem('V17', 'تتوفر الأسرة على مرآب', 0.117, 'checkbox')
    yield MetricItem('V18', 'تتوفر الأسرة على محالت مهنية', 0.111, 'checkbox')

    # Quantity questions
    yield MetricItem('V19', 'عدد أفراد الأسرة', -0.177, 'text-input')
    yield MetricItem('V20', 'مربع عدد أفراد الأسرة', 0.00533, 'text-input')
    yield MetricItem('V21', 'سن رب الأسرة', -0.0104, 'text-input')
    yield MetricItem('V22', 'ربع سن رب األسر', 0.0000771, 'text-input')
    yield MetricItem('V23', 'عدد األطفال املتمدرسين في القطاع الخاص الذين تتراوح أعمارهم ما بين 6 و 14 سنة', 0.105, 'text-input')
    yield MetricItem('V24', 'عدد األطفال املتمدرسين في القطاع العمومي الذين تتراوح أعمارهم ما بين 6 و 14 سنة', -0.0319, 'text-input')
    yield MetricItem('V25', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثر والذين ال يتوفرون على أي شهادة', -0.0557, 'text-input')
    yield MetricItem('V26', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثر الحاصلين على شهادة أو دبلوم تقني', 0.120, 'text-input')
    yield MetricItem('V27', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثرالذين يزاولون نشاطا مدرا للدخل', 0.139, 'text-input')
    yield MetricItem('V28', 'نسبة أفراد الأسرة الذين تبلغ أعمارهم 15 سنة فأكثرالذين يزاولون نشاط تسيير للمعدات', 0.307, 'text-input')
    yield MetricItem('V29', 'نسبة أفراد الأسرة الذين يشتغلون كأطرعليا أو يشغلون منصب مسؤولية', 0.180, 'text-input')
    yield MetricItem('V30', 'عدد الهواتف املحمولة داخل الأسرة', 0.0516, 'text-input')
    yield MetricItem('V31', 'عدد السيارات في حوزة األسر', 0.226, 'text-input')
    yield MetricItem('V32', 'دد الدراجات النارية', 0.0598, 'text-input')
    yield MetricItem('V33', 'مبلغ مصاريف الأسرة السنوية املتعلقة باستهالك غازالبوتان مقسوم على عدد أفراد الأسرة', 0.000422, 'text-input')
    yield MetricItem('V34', 'مبلغ مصاريف الأسرة السنوية املتعلقة باستهالك املاء والكهرباء مقسوم على عدد أفراد الأسرة', 0.00011, 'text-input')
    yield MetricItem('V35', 'مبلغ مصاريف لألسرة السنوية املتعلقة باستهالك الهاتف واإلنترنت مقسوم على عدد أفراد الأسرة', 0.000302, 'text-input')

    # Select questions
    yield MetricItem('KZG1', 'طنجة-تطوان-الحسيمة', 0.107, 'select-input')
    yield MetricItem('KZG2', 'الشرق', 0.196, 'select-input')
    yield MetricItem('KZG3', 'فاس-مكناس', 0.123, 'select-input')
    yield MetricItem('KZG4', 'الرباط - سال- القنيطرة', 0.0555, 'select-input')
    yield MetricItem('KZG5', 'بني مالل - خنيفرة', 0.0, 'select-input')
    yield MetricItem('KZG6', 'الدار البيضاء - سطات', 0.220, 'select-input')
    yield MetricItem('KZG7', 'مراكش - آسفي', 0.194, 'select-input')
    yield MetricItem('KZG8', 'درعة - تافياللت', 0.0, 'select-input')
    yield MetricItem('KZG9', 'سوس - ماسة', 0.0, 'select-input')
    yield MetricItem('KZG10', 'كلميم - واد نون', 0.285, 'select-input')
    yield MetricItem('KZG11', 'العيون-الساقية الحمراء ', 0.285, 'select-input')
    yield MetricItem('KZG12', 'الداخلة-وادي الذهبرة', 0.285, 'select-input')




def make_smr_metrics():
    yield MetricItem('V1', '', 0)
    yield MetricItem('V2', '', 0)
    yield MetricItem('V3', '', 0)
    yield MetricItem('V4', '', 0)
    yield MetricItem('V5', '', 0)
    yield MetricItem('V6', '', 0)
    yield MetricItem('V7', '', 0)
    yield MetricItem('V8', '', 0)
    yield MetricItem('V9', '', 0)
    yield MetricItem('V10', '', 0)
    yield MetricItem('V11', '', 0)
    yield MetricItem('V12', '', 0)
    yield MetricItem('V13', '', 0)
    yield MetricItem('V14', '', 0)
    yield MetricItem('V15', '', 0)
    yield MetricItem('V16', '', 0)
    yield MetricItem('V17', '', 0)
    yield MetricItem('V18', '', 0)
    yield MetricItem('V19', '', 0)
    yield MetricItem('V20', '', 0)
    yield MetricItem('V21', '', 0)
    yield MetricItem('V22', '', 0)
    yield MetricItem('V23', '', 0)
    yield MetricItem('V24', '', 0)
    yield MetricItem('V25', '', 0)
    yield MetricItem('V26', '', 0)
    yield MetricItem('V27', '', 0)
    yield MetricItem('V28', '', 0)
    yield MetricItem('V29', '', 0)
    yield MetricItem('V30', '', 0)
    yield MetricItem('V31', '', 0)
    yield MetricItem('V32', '', 0)
    yield MetricItem('V33', '', 0)
    yield MetricItem('V34', '', 0)
    yield MetricItem('V35', '', 0)

    yield MetricItem('KZG1', '', 0)
    yield MetricItem('KZG2', '', 0)
    yield MetricItem('KZG3', '', 0)
    yield MetricItem('KZG4', '', 0)
    yield MetricItem('KZG5', '', 0)
    yield MetricItem('KZG6', '', 0)
    yield MetricItem('KZG7', '', 0)
    yield MetricItem('KZG8', '', 0)
    yield MetricItem('KZG9', '', 0)
    yield MetricItem('KZG10', '', 0)
    yield MetricItem('KZG11', '', 0)
    yield MetricItem('KZG12', '', 0)
